# Generated by Django 4.2 on 2025-12-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shorturl', models.URLField(max_length=10)),
                ('originalurl', models.URLField(max_length=100)),
                ('addedUrl', models.BooleanField(default=True)),
            ],
        ),
    ]
