# Generated by Django 4.2 on 2025-12-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='originalurl',
            field=models.URLField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='urls',
            name='shorturl',
            field=models.URLField(max_length=10, unique=True),
        ),
    ]
