# Generated by Django 4.2 on 2025-12-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_urls_originalurl_alter_urls_shorturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='addedUrl',
            field=models.IntegerField(),
        ),
    ]
