# Generated by Django 5.2.11 on 2026-02-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_otpverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
