# Generated by Django 4.2 on 2026-01-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_shorturl_click_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
