# Generated by Django 6.0.1 on 2026-01-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_clckevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClckEvent',
            new_name='ClickEvent',
        ),
    ]
