# Generated by Django 6.0.1 on 2026-02-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_clckevent_clickevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='device_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
