# Generated by Django 6.0.1 on 2026-02-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_clickevent_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
