# Generated by Django 6.0.1 on 2026-02-08 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_shorturl_short_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['short_code'], name='app_shortur_short_c_c5e581_idx'),
        ),
    ]
