# Generated by Django 5.2.11 on 2026-02-09 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_shorturlcore_shorturlmeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='short_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='app.shorturlcore'),
        ),
    ]
