# Generated by Django 5.2.11 on 2026-02-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_clickevent_short_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortURL',
        ),
    ]
