# Generated by Django 5.2.11 on 2026-02-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_activation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
